### ISSUE TITLE
No form_definition available in selection

### ISSUE THREAD

**Issue by herrhamann** [extcode/cart_events#60]
When editing the event record, the selection for form_definitions is empty. Shouldn't at least the Example Form be present? Or do I have to integrate them by myself? Then some explanation in the docs would be helpful.

Greets Alex

**Comment by extcode** [comment]
There is no sample form included in the extension. However, the extension contains a form template. With the option "Advanced settings" when creating a new form in the form management, you get a selection for "Form prototype" and "Start template" in step 2. Here you can select the prototype "cart events".
The event record does not allow normal forms, but forms from the corresponding prototype, because it brings special fields (through PHP code) and has a corresponding finisher ready.

I will try to write a corresponding instruction in the documentation soon.

I hope that this helps you for the time being.
